name: smartspend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.7.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.17.4
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  shared_preferences: ^2.5.3
  csv: ^6.0.0
  path_provider: ^2.1.5
  share_plus: ^10.0.0
  file_picker: ^8.0.7
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
